version: 2.1

orbs:
  node: circleci/node@7.1.0
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install dependencies
          command: npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test

  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24  # Enables Docker commands in CircleCI
      - docker/check  # Validates Docker setup
      - docker/build:
          image: fatb0y13/education-space  # Docker image name
          tag: latest  # Tag for the Docker image
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin  # Log in to Docker Hub
      - docker/push:
          image: fatb0y13/education-space  # Image name for pushing to Docker Hub
          tag: latest  # Push the 'latest' tag

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build  # 'test' job depends on 'build'
      - build-and-push:
          requires:
            - test  # 'build-and-push' job depends on 'test'